### ISSUE TITLE
How to get an invitation?

### ISSUE THREAD

**Issue by dotcs** [komoot/komoot-oauth2-connect-example#2]
From the readme:

> This feature is currently in beta, you need an invitation to use it.

I'm interested in the API for writing software that automatically processes data generated via Komoot. Is it possible for me to participate in the beta program?

**Comment by jtheuer** [comment]
Hey dotcs, thanks for your interest! We compiled all information here: https://www.komoot.de/b2b/connect#profileconnect

I'll add the link to the readme as well!
