### ISSUE TITLE
How does it works ?

### ISSUE THREAD

**Issue by ArthurREGNARD** [komoot/komoot-oauth2-connect-example#4]
Hello, 
I try to connect to the Komoot API. The documentation found here told me to try a connection with your script : https://static.komoot.de/doc/auth/oauth2.html

In your script, by default, the base-url is : https://auth.komoot.de/   but I'm in France ...
In the documentation, they say to use the base url : https://auth-api.main.komoot.net

Where can I found a documentation to connect the Komoot server API ?

**Comment by ArthurREGNARD** [comment]
@jtheuer @danielgard @JorgenG @lukaswelte 
Any one here ?

**Comment by ArthurREGNARD** [comment]
When I go to : https://auth.komoot.de/oauth/authorize?response_type=code&client_id=2212109527294&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fcallback&state=BeA7Fi4HiwPi68vC7YoIoXEEcFR5GY

I get: 
```bash
OAuth Error

error="invalid_client", error_description="Bad client credentials"
```

**Comment by jtheuer** [comment]
Hi @ArthurREGNARD check the documentation here https://github.com/komoot/komoot-oauth2-connect-example#komoot-oauth2-connect-example - you need to apply for credentials in order to use this integration.
